# .github/workflows/deploy.yml

name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Login to Azure Container Registry
      run: az acr login --name your-acr-name

    - name: Build and Push Docker Image
      run: |
        docker build -t your-image-name .
        docker tag your-image-name your-acr-name.azurecr.io/your-image-name:latest
        docker push your-acr-name.azurecr.io/your-image-name:latest

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/your-deployment-name your-container-name=your-acr-name.azurecr.io/your-image-name:latest

    - name: Check Deployment Status
      run: kubectl rollout status deployment/your-deployment-name
